In [122]:
import pandas as pd

In [123]:
datasets = pd.read_csv('../data/raw/loan_data.csv')
datasets.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [124]:
# %%
datasets.info()
# %%
# datasets.describe()
# # %%

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [125]:
datasets.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [126]:
print(datasets["Gender"].value_counts())
print(datasets["Education"].value_counts())
print(datasets["Dependents"].value_counts())
print(datasets["Self_Employed"].value_counts())
print(datasets["Married"].value_counts())

Gender
Male      489
Female    112
Name: count, dtype: int64
Education
Graduate        480
Not Graduate    134
Name: count, dtype: int64
Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64
Self_Employed
No     500
Yes     82
Name: count, dtype: int64
Married
Yes    398
No     213
Name: count, dtype: int64

In [127]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')

In [128]:
datasets["Gender"] = imputer.fit_transform(datasets[["Gender"]]).ravel()
datasets['Married'] = imputer.fit_transform(datasets[['Married']]).ravel()
datasets['Dependents'] = imputer.fit_transform(datasets[['Dependents']]).ravel()
datasets['Self_Employed'] = imputer.fit_transform(datasets[['Self_Employed']]).ravel()
datasets['LoanAmount'] = imputer.fit_transform(datasets[['LoanAmount']]).ravel()
datasets['Loan_Amount_Term'] = imputer.fit_transform(datasets[['Loan_Amount_Term']]).ravel()

In [129]:
datasets.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [130]:
datasets.head(30)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,120.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,No,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,No,2600,3500.0,115.0,360.0,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,Male,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,No,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,LP001087,Female,No,2,Graduate,No,3750,2083.0,120.0,360.0,1.0,Semiurban,Y

In [131]:
print(datasets["Gender"].value_counts())
print(datasets["Education"].value_counts())
print(datasets["Dependents"].value_counts())
print(datasets["Self_Employed"].value_counts())
print(datasets["Married"].value_counts())
print(datasets["Property_Area"].value_counts())
print(datasets["Loan_Status"].value_counts())
print(datasets["Credit_History"].value_counts())

Gender
Male      502
Female    112
Name: count, dtype: int64
Education
Graduate        480
Not Graduate    134
Name: count, dtype: int64
Dependents
0     360
1     102
2     101
3+     51
Name: count, dtype: int64
Self_Employed
No     532
Yes     82
Name: count, dtype: int64
Married
Yes    401
No     213
Name: count, dtype: int64
Property_Area
Semiurban    233
Urban        202
Rural        179
Name: count, dtype: int64
Loan_Status
Y    422
N    192
Name: count, dtype: int64
Credit_History
1.0    475
0.0     89
Name: count, dtype: int64

In [132]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

labelencoder = LabelEncoder()
hotencoder = OneHotEncoder()
scaler = StandardScaler()

In [133]:
datasets["Gender"] = labelencoder.fit_transform(datasets["Gender"])
mapping = {label: idx for idx, label in enumerate(labelencoder.classes_)}
print(mapping, "Gender mapping \n")

datasets["Married"] = labelencoder.fit_transform(datasets["Married"])
mapping = {label: idx for idx, label in enumerate(labelencoder.classes_)}
print(mapping, "Married mapping \n")

datasets["Education"] = labelencoder.fit_transform(datasets["Education"])
mapping = {label: idx for idx, label in enumerate(labelencoder.classes_)}
print(mapping, "Education mapping \n")

datasets["Self_Employed"] = labelencoder.fit_transform(datasets["Self_Employed"])
mapping = {label: idx for idx, label in enumerate(labelencoder.classes_)}
print(mapping, "Self_Employed mapping \n")

{'Female': 0, 'Male': 1} Gender mapping

{'No': 0, 'Yes': 1} Married mapping

{'Graduate': 0, 'Not Graduate': 1} Education mapping

{'No': 0, 'Yes': 1} Self_Employed mapping

In [134]:
datasets.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,0,0,0,0,5849,0.0,120.0,360.0,1.0,Urban,Y
1,LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,1,1,2,0,1,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,1,1,0,1,0,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,1,1,3+,0,0,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,1,1,2,0,0,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,1,1,1,0,0,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,1,1,2,0,0,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,1,1,2,0,0,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,1,1,2,0,0,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,1,0,0,0,0,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,1,1,2,0,0,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,1,0,0,0,0,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,1,0,1,1,0,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,0,0,0,0,0,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,1,1,0,1,0,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,1,1,0,0,0,2600,3500.0,115.0,360.0,1.0,Urban,Y

In [135]:
# encode property area too
datasets["Property_Area"] = labelencoder.fit_transform(datasets["Property_Area"])
mapping = {label: idx for idx, label in enumerate(labelencoder.classes_)}
print(mapping, "Property_Area mapping \n")

{'Rural': 0, 'Semiurban': 1, 'Urban': 2} Property_Area mapping

In [136]:
datasets.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1,0,0,0,0,5849,0.0,120.0,360.0,1.0,2,Y
1,LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,Y
5,LP001011,1,1,2,0,1,5417,4196.0,267.0,360.0,1.0,2,Y
6,LP001013,1,1,0,1,0,2333,1516.0,95.0,360.0,1.0,2,Y
7,LP001014,1,1,3+,0,0,3036,2504.0,158.0,360.0,0.0,1,N
8,LP001018,1,1,2,0,0,4006,1526.0,168.0,360.0,1.0,2,Y
9,LP001020,1,1,1,0,0,12841,10968.0,349.0,360.0,1.0,1,N
10,LP001024,1,1,2,0,0,3200,700.0,70.0,360.0,1.0,2,Y
11,LP001027,1,1,2,0,0,2500,1840.0,109.0,360.0,1.0,2,Y
12,LP001028,1,1,2,0,0,3073,8106.0,200.0,360.0,1.0,2,Y
13,LP001029,1,0,0,0,0,1853,2840.0,114.0,360.0,1.0,0,N
14,LP001030,1,1,2,0,0,1299,1086.0,17.0,120.0,1.0,2,Y
15,LP001032,1,0,0,0,0,4950,0.0,125.0,360.0,1.0,2,Y
16,LP001034,1,0,1,1,0,3596,0.0,100.0,240.0,NaN,2,Y
17,LP001036,0,0,0,0,0,3510,0.0,76.0,360.0,0.0,2,N
18,LP001038,1,1,0,1,0,4887,0.0,133.0,360.0,1.0,0,N
19,LP001041,1,1,0,0,0,2600,3500.0,115.0,360.0,1.0,2,Y

In [137]:
# hot encode dependents
Dependents_onehot = hotencoder.fit_transform(datasets[["Dependents"]]).toarray()

In [138]:
Dependents_datasets = pd.DataFrame(Dependents_onehot, columns=hotencoder.get_feature_names_out(["Dependents"]))
print(Dependents_datasets, "Dependents encoded \n")

     Dependents_0  Dependents_1  Dependents_2  Dependents_3+
0             1.0           0.0           0.0            0.0
1             0.0           1.0           0.0            0.0
2             1.0           0.0           0.0            0.0
3             1.0           0.0           0.0            0.0
4             1.0           0.0           0.0            0.0
..            ...           ...           ...            ...
609           1.0           0.0           0.0            0.0
610           0.0           0.0           0.0            1.0
611           0.0           1.0           0.0            0.0
612           0.0           0.0           1.0            0.0
613           1.0           0.0           0.0            0.0

[614 rows x 4 columns] Dependents encoded

In [139]:
Dependents_datasets.head()

   Dependents_0  Dependents_1  Dependents_2  Dependents_3+
0           1.0           0.0           0.0            0.0
1           0.0           1.0           0.0            0.0
2           1.0           0.0           0.0            0.0
3           1.0           0.0           0.0            0.0
4           1.0           0.0           0.0            0.0

In [140]:
datasets = pd.concat([datasets, Dependents_datasets], axis=1)

In [141]:
datasets.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Dependents_0,Dependents_1,Dependents_2,Dependents_3+
0,LP001002,1,0,0,0,0,5849,0.0,120.0,360.0,1.0,2,Y,1.0,0.0,0.0,0.0
1,LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,N,0.0,1.0,0.0,0.0
2,LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,Y,1.0,0.0,0.0,0.0
3,LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,Y,1.0,0.0,0.0,0.0
4,LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,Y,1.0,0.0,0.0,0.0

In [142]:
# encode loan status
datasets["Loan_Status"] = labelencoder.fit_transform(datasets["Loan_Status"])

In [143]:
datasets.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Dependents_0,Dependents_1,Dependents_2,Dependents_3+
0,LP001002,1,0,0,0,0,5849,0.0,120.0,360.0,1.0,2,1,1.0,0.0,0.0,0.0
1,LP001003,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0,0.0,1.0,0.0,0.0
2,LP001005,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1,1.0,0.0,0.0,0.0
3,LP001006,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1,1.0,0.0,0.0,0.0
4,LP001008,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1,1.0,0.0,0.0,0.0

In [144]:
# get the mappings for all the encoded columns (for gender, it should be {"Male": 1, "Female": 0})
print(datasets["Gender"].value_counts())

Gender
1    502
0    112
Name: count, dtype: int64

In [145]:
# drop loanid and dependents
datasets = datasets.drop(["Loan_ID", "Dependents", "CoapplicantIncome", "Credit_History"], axis=1)
datasets.head()

,Gender,Married,Education,Self_Employed,ApplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status,Dependents_0,Dependents_1,Dependents_2,Dependents_3+
0,1,0,0,0,5849,120.0,360.0,2,1,1.0,0.0,0.0,0.0
1,1,1,0,0,4583,128.0,360.0,0,0,0.0,1.0,0.0,0.0
2,1,1,0,1,3000,66.0,360.0,2,1,1.0,0.0,0.0,0.0
3,1,1,1,0,2583,120.0,360.0,2,1,1.0,0.0,0.0,0.0
4,1,0,0,0,6000,141.0,360.0,2,1,1.0,0.0,0.0,0.0

In [146]:
# scale the loan amount and loan amount term
datasets[["LoanAmount"]] = scaler.fit_transform(datasets[["LoanAmount"]])
datasets[["Loan_Amount_Term"]] = scaler.fit_transform(datasets[["Loan_Amount_Term"]])
datasets[["ApplicantIncome"]] = scaler.fit_transform(datasets[["ApplicantIncome"]])

In [147]:
datasets.head()

,Gender,Married,Education,Self_Employed,ApplicantIncome,LoanAmount,Loan_Amount_Term,Property_Area,Loan_Status,Dependents_0,Dependents_1,Dependents_2,Dependents_3+
0,1,0,0,0,0.072991,-0.302759,0.273231,2,1,1.0,0.0,0.0,0.0
1,1,1,0,0,-0.134412,-0.207648,0.273231,0,0,0.0,1.0,0.0,0.0
2,1,1,0,1,-0.393747,-0.944757,0.273231,2,1,1.0,0.0,0.0,0.0
3,1,1,1,0,-0.462062,-0.302759,0.273231,2,1,1.0,0.0,0.0,0.0
4,1,0,0,0,0.097728,-0.053093,0.273231,2,1,1.0,0.0,0.0,0.0

In [148]:
# save to csv
datasets.to_csv('../data/processed/loan_data_processed.csv', index=False)

In [149]:
import pickle

# Save model + preprocessors
with open('../models/preprocessor.pkl', 'wb') as f:
    pickle.dump({
        'imputer': imputer,
        'labelencoder': labelencoder,
        'hotencoder': hotencoder
    }, f)